- name: Deploy a web application
  #strategy: linear # free
  #serial: 1
  #serial:
  #  - 1
  #  - 1
  #serial: "50%"
  #any_errors_fatal: true
  hosts: db_and_web_server1, db_and_web_server2
  roles:
    - python
    - mysql_db
    - flask_web
