- name: Deploy a web application
  hosts: db_and_web_server1, db_and_web_server2
  tasks:
    - name: İnstall all required dependencies
      apt: name={{ item }} state=present
      with_items:
        - python
        - python-setuptools
        - python-dev
        - build-essential
        - pip
    - include: tasks/deploy_db.yaml
    - include: tasks/deploy_web.yaml
