- name: Install all required dependencies
  apt: name={{ item }} state=present
  with_items:
    - python
    - python-setuptools
    - python-dev
    - build-essential
    - pip
    - python3-mysqldb
